#!/usr/bin/env python
# coding: utf-8

# # Learning Stable Control-oriented Deep Koopman Operators  
# 
# 
# This tutorial demonstrates the use of [Deep Koopman Operators](https://www.nature.com/articles/s41467-018-07210-0) (DeepKO) with stability guarantees for system identificaiton of nonautonomous nonlinear dynamical systems in NeuroMANCER. 
# 
# 
# ## Koopman System Identification with Control Problem Setup
# 
# <img src="../figs/Koopman_model.png" width="500">  
# 
# 
# System observables  $y_{k}$ and control inputs $u_k$ are encoded via encoder neural networks $f_y$ and $f_u$ to generate latent states $x_{k}$ (linear coordinates). This coordinate transformation now allos to apply linear Koopman operator $K$ to obtain latent states at the next time step $x_{k+1}$. After the rollout over given prediction horizon $N$ the generated latent trajectories $\{x_1, ..., x_N \}$ are proejcted back to the observable space via decoder neural network $f_y^{-1}$.
# Now this Koopman encoder-decoder model can be trained as any other black-box nonlinear system identification problem with the loss $\mathcal{L}$ evaluated by comparing the  trajectory generated by the model with the training trajectory. 
# 
# 
# ### Koopman with Control References
# 
# [1] [H. Shi and M. Q. . -H. Meng, "Deep Koopman Operator With Control for Nonlinear Systems," in IEEE Robotics and Automation Letters, vol. 7, no. 3, pp. 7700-7707, July 2022, doi: 10.1109/LRA.2022.3184036.](https://ieeexplore.ieee.org/document/9799788)  
# [2] [Eurika Kaiser and J Nathan Kutz and Steven L Brunton, Data-driven discovery of Koopman eigenfunctions for control, Mach. Learn.: Sci. Technol. 2021](https://iopscience.iop.org/article/10.1088/2632-2153/abf0f5)  
# [3] [M. Korda and I. Mezić, "Optimal Construction of Koopman Eigenfunctions for Prediction and Control," in IEEE Transactions on Automatic Control, vol. 65, no. 12, pp. 5114-5129, Dec. 2020](https://ieeexplore.ieee.org/document/9022864)  
# [4] [Yiqiang Han, Wenjian Hao, Umesh Vaidya, Deep Learning of Koopman Representation for Control, 2020
# ](https://arxiv.org/abs/2010.07546)  
# [6] [Minghao Han, Jacob Euler-Rolle, Robert K. Katzschmann, DeSKO: Stability-Assured Robust Control with a Deep Stochastic Koopman Operator, ICLR 2022](https://openreview.net/forum?id=hniLRD_XCA)  
# [6] https://github.com/HaojieSHI98/DeepKoopmanWithControl
# 
# 
# ### Generic Stable Layers References
# [7]  [E. Skomski, S. Vasisht, C. Wight, A. Tuor, J. Drgoňa and D. Vrabie, "Constrained Block Nonlinear Neural Dynamical Models," 2021 American Control Conference (ACC), New Orleans, LA, USA, 2021, pp. 3993-4000](https://ieeexplore.ieee.org/document/9482930)   
# [8] [J. Drgoňa, A. Tuor, S. Vasisht and D. Vrabie, "Dissipative Deep Neural Dynamical Systems," in IEEE Open Journal of Control Systems, 2022](https://ieeexplore.ieee.org/abstract/document/9809789)  
# [9] [Jiong Zhang, Qi Lei, Inderjit S. Dhillon, Stabilizing Gradients for Deep Neural Networks via Efficient SVD Parameterization, InternationalConferenceonMachine Learning, 2018](https://arxiv.org/abs/1803.09327)
# 
# 

# ## NeuroMANCER and Dependencies

# In[ ]:





# ### Install (Colab only)
# Skip this step when running locally.

# In[ ]:





# In[ ]:


import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import pickle 
import scipy
import time as tim

from neuromancer.psl import plot
from neuromancer import psl
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

from neuromancer.system import Node, System
from neuromancer.slim import slim
from neuromancer.trainer import Trainer
from neuromancer.problem import Problem
from neuromancer.dataset import DictDataset
from neuromancer.constraint import variable
from neuromancer.loss import PenaltyLoss
from neuromancer. modules import blocks
import joblib

from sklearn.preprocessing import StandardScaler, MinMaxScaler
torch.manual_seed(0)


# ## Generate trajectories from ODE system 
# 
# In this example we don't assume any prior knowledge on the system dynamics. We will only have access to limited measurements of the system states $x$ of an unknown [ordinary differential equations](https://en.wikipedia.org/wiki/Ordinary_differential_equation) (ODE).
# 
# Select the system_name from the available list of [nonautonomous ODE systems](https://github.com/pnnl/neuromancer/blob/master/src/neuromancer/psl/nonautonomous.py):
# - TwoTank
# - CSTR
# - SwingEquation
# - IverSimple

# # Get and save data - (Already done)

# ## Create training data of sampled trajectories
# 
# We will obtain a dataset of sampled trajectories of the system dynamics in the form of input-state tuples: 
# $$D = \big[(u^i_0, \hat{x}^i_0), ..., (u^i_N, \hat{x}^i_{N}) \big], \, \, i \in [1, ..., m]$$
# where $N$ represents the prediction horizon, $m$ represents number of measured trajectories, and $i$ represents an index of the sampled trajectory.
# Variables $x_k$ represent system states, and $u_k$ are exogenous inputs at time $k$.

# 

# ## Deep Koopman model in Neuromancer
# 
# Here we construct a discrete-time encoder-decoder Koopman model with control:   
# 
# <img src="../figs/Koopman_model.png" width="500">  
# 
# 
# Encoder: $${x}_{k} = f_y(y_k) +f_u(u_k)$$ 
# Koopman: $${x}_{k+1} = K(x_k)$$ 
# Decoder: $$\hat{y}_{k+1} = f_y^{-1}(x_{k+1})$$  

# In[ ]:





# In[ ]:


import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import pickle 
import scipy
import time as tim

from neuromancer.psl import plot
from neuromancer import psl
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

from neuromancer.system import Node, System
from neuromancer.slim import slim
from neuromancer.trainer import Trainer
from neuromancer.problem import Problem
from neuromancer.dataset import DictDataset
from neuromancer.constraint import variable
from neuromancer.loss import PenaltyLoss
from neuromancer. modules import blocks
import joblib

from sklearn.preprocessing import StandardScaler
torch.manual_seed(0)


# ## Generate trajectories from ODE system 
# 
# In this example we don't assume any prior knowledge on the system dynamics. We will only have access to limited measurements of the system states $x$ of an unknown [ordinary differential equations](https://en.wikipedia.org/wiki/Ordinary_differential_equation) (ODE).
# 
# Select the system_name from the available list of [nonautonomous ODE systems](https://github.com/pnnl/neuromancer/blob/master/src/neuromancer/psl/nonautonomous.py):
# - TwoTank
# - CSTR
# - SwingEquation
# - IverSimple

# # Get and save data - (Already done)

# ## Create training data of sampled trajectories
# 
# We will obtain a dataset of sampled trajectories of the system dynamics in the form of input-state tuples: 
# $$D = \big[(u^i_0, \hat{x}^i_0), ..., (u^i_N, \hat{x}^i_{N}) \big], \, \, i \in [1, ..., m]$$
# where $N$ represents the prediction horizon, $m$ represents number of measured trajectories, and $i$ represents an index of the sampled trajectory.
# Variables $x_k$ represent system states, and $u_k$ are exogenous inputs at time $k$.

# 

# In[ ]:


# with open('data/train_real.pkl', 'rb') as fp:
#         train_sim = pickle.load(fp)

# with open('data/test_real.pkl', 'rb') as fp:
#         test_sim = pickle.load(fp)


# In[ ]:


from scipy.io import loadmat

""" #data = loadmat('data.mat')"""


test_data = loadmat('test_data_ident.mat')
train_data = loadmat('train_data_ident.mat')

"""
# Explore the content


print(train_data['Utrain'].shape)
print(train_data['Ytrain'].shape)

print(test_data['Utest'].shape)
print(test_data['Ytest'].shape) """

""" print(test_data['U'].shape)
print(test_data['Y'].shape)
print(test_data['X'].shape)
print(test_data['U'].shape) """
""" 
print(data['U'].shape)
print(data.keys())
print(data['U'].shape) """


# In[ ]:


Y_train = train_data['Ytrain']
U_train = train_data['Utrain']
Y_test = test_data['Ytest']
U_test = test_data['Utest']


# In[ ]:


train_sim = {'Y': Y_train, 'U': U_train}
test_sim = {'Y': Y_test, 'U': U_test}


# In[ ]:





# In[ ]:


def get_data(train_sim, test_sim, nx, nu, nsteps, bs, scaler, scalerU):
    dev_sim = train_sim

    # Combine training and test data for reshaping
    trainY = np.vstack((train_sim['Y'], test_sim['Y']))
    trainU = np.vstack((train_sim['U'], test_sim['U']))

    nsim = trainY.shape[0]
    nbatch = nsim // nsteps
    length = nbatch * nsteps

    trainX = scaler.transform(trainY[:length]).reshape(nbatch, nsteps, nx)
    trainU = scalerU.transform(trainU[:length]).reshape(nbatch, nsteps, nu)

    train_dataset = DictDataset({
        'Y': torch.tensor(trainX, dtype=torch.float32),
        'Y0': torch.tensor(trainX[:, 0:1, :], dtype=torch.float32),
        'U': torch.tensor(trainU, dtype=torch.float32)
    }, name='train')

    train_loader = DataLoader(train_dataset, batch_size=bs,
                              collate_fn=train_dataset.collate_fn, shuffle=True)

    # Dev set
    nsim = dev_sim['Y'].shape[0]
    nbatch = nsim // nsteps
    length = nbatch * nsteps

    devX = scaler.transform(dev_sim['Y'][:length]).reshape(nbatch, nsteps, nx)
    devU = scalerU.transform(dev_sim['U'][:length]).reshape(nbatch, nsteps, nu)

    dev_dataset = DictDataset({
        'Y': torch.tensor(devX, dtype=torch.float32),
        'Y0': torch.tensor(devX[:, 0:1, :], dtype=torch.float32),
        'U': torch.tensor(devU, dtype=torch.float32)
    }, name='dev')

    dev_loader = DataLoader(dev_dataset, batch_size=bs,
                            collate_fn=dev_dataset.collate_fn, shuffle=True)

    # Test set (single trajectory)
    nsim = test_sim['Y'].shape[0]
    nbatch = nsim // nsteps
    length = nbatch * nsteps

    testX = scaler.transform(test_sim['Y'][:length]).reshape(1, nbatch * nsteps, nx)
    testU = scalerU.transform(test_sim['U'][:length]).reshape(1, nbatch * nsteps, nu)

    test_data = {
        'Y': torch.tensor(testX, dtype=torch.float32),
        'Y0': torch.tensor(testX[:, 0:1, :], dtype=torch.float32),
        'U': torch.tensor(testU, dtype=torch.float32)
    }

    return train_loader, dev_loader, test_data


# In[ ]:


#train_sim = data
#test_data = data

nsim = train_sim['Y'].shape[0]   # number of simulation steps in the dataset
nsteps = 80   # number of prediction horizon steps in the loss function
bs = 100      # minibatching batch size

#skalovanie

scaler = StandardScaler()
scaler.fit(train_sim['Y'])  # Fit only on training data
joblib.dump(scaler, 'data/scaler.pkl')

scalerU = StandardScaler()
scalerU.fit(train_sim['U'])
joblib.dump(scalerU, 'data/scalerU.pkl')

nx = train_sim['Y'].shape[1]
ny = train_sim['Y'].shape[1]
nu = train_sim['U'].shape[1]

train_loader, dev_loader, test_data = get_data(
    train_sim, test_sim, nx, nu, nsteps, bs, scaler, scalerU
)


# In[ ]:


scaler.inverse_transform([[0]])


# In[ ]:


print("Mean:", scaler.mean_)            # The mean value for each feature
print("Scale (std dev):", scaler.scale_)  # The standard deviation for each feature
print("Var:", scaler.var_)      


# In[ ]:


# model parameters
nx_koopman = 10
n_hidden = 60
n_layers = 3
layers = [60, 60, 60]


# **Encoder and Decoder networks** 

# In[ ]:


# instantiate output encoder neural net f_y
f_y = blocks.MLP(
    ny,
    nx_koopman,
    bias=True,
    linear_map=torch.nn.Linear,
    nonlin=torch.nn.ReLU,
    hsizes=layers,
)
# initial condition encoder
encode_Y0 = Node(f_y, ['Y0'], ['x'], name='encoder_Y0')
# observed trajectory encoder
encode_Y = Node(f_y, ['Y'], ['x_latent'], name='encoder_Y')


# In[ ]:


# instantiate input encoder net f_u

f_u = torch.nn.Linear(nu, nx_koopman, bias=False)
# initial condition encoder
encode_U = Node(f_u, ['U'], ['u_latent'], name='encoder_U')


# In[ ]:


# instantiate state decoder neural net f_y_inv
f_y_inv = blocks.MLP(nx_koopman, ny, bias=True,
                linear_map=torch.nn.Linear,
                nonlin=torch.nn.ELU,
                hsizes=layers)
#f_y_inv = torch.nn.Linear(nx_koopman, ny, bias=False)
# predicted trajectory decoder
decode_y = Node(f_y_inv, ['x'], ['yhat'], name='decoder_y')


# **Standard Koopman Operator** without stability guarantees is parametrized by linear layer of the latent size. 
# 
# **Stable Koopman Operator:**  For provably stable Koopman operator we can choose a range of linear algebra factorization that allow to constrain the eigenvalues of the resulting linear operator. 
# In this example we use the following [Singular Value Decomposition (SVD)](https://en.wikipedia.org/wiki/Singular_value_decomposition) factorization of the operator given as:
# $$K = U \Sigma V$$ 
# $$\Sigma =  \text{diag}(\lambda_{\text{max}} - (\lambda_{\text{max}} - \lambda_{\text{min}}) \cdot \sigma(\Lambda)) $$
# where $\sigma$ is logistic sigmoid activation function, $\cdot$ is a dot product, $\Lambda$ is a vector of eigenvalues of the linear operator, while $\lambda_{\text{max}}$ and $\lambda_{\text{min}}$ are constraints on maximum and minimum value of SVD factorized linear operator.
# 
# <img src="../figs/SVD_layer.png" width="300">  
# 
# In order for the SVD factorization to hold the left and right matrices $U$ and $V$, respectively, needs to be [orthogonal](https://en.wikipedia.org/wiki/Orthogonal_matrix).
# This can be achieved either via [Householder reflectors](https://arxiv.org/abs/1803.09327), or via penalties in the loss function given as:  
# $$\ell_{U} = || I - UU^T||_2 + || I - U^TU||_2  $$
# $$\ell_{V} = || I - VV^T||_2 + || I - V^TV||_2  $$
# $$\ell_{\text{stable}} = \ell_{U} + \ell_{V} $$
# 
# For more details on the SVD and other linear algebra factorizations of trainable linear layers see the references [[7]](https://ieeexplore.ieee.org/document/9482930) and [[8]](https://ieeexplore.ieee.org/abstract/document/9809789), with Pytorch implementations in the [slim submodule](https://github.com/pnnl/neuromancer/tree/master/src/neuromancer/slim) of the Neuromancer library. 

# In[ ]:


# instantiate Koopman operator matrix
stable = False     # if True then provably stable Koopman operator
if stable:
    # SVD factorized Koopman operator with bounded eigenvalues: sigma_min <= \lambda_i <= sigma_max
    K = slim.linear.SVDLinear(nx_koopman, nx_koopman,
                          sigma_min=0.01, sigma_max=1.0, bias=False)
    # SVD penalty variable
    K_reg_error = variable(K.reg_error())
    # SVD penalty loss term
    K_reg_loss = 1.*(K_reg_error == 0.0)
    K_reg_loss.name = 'SVD_loss'
else:
    # linear Koopman operator without guaranteed stability
    K = torch.nn.Linear(nx_koopman, nx_koopman, bias=False)


# In[ ]:


class Koopman_control(nn.Module):
    """
    Baseline class for Koopman control model
    Implements discrete-time dynamical system:
        x_k+1 = K x_k + u_k
    with variables:
        x_k - latent states
        u_k - latent control inputs
    """

    def __init__(self, K):
        super().__init__()
        self.K = K

    def forward(self, x, u):
        """
        :param x: (torch.Tensor, shape=[batchsize, nx])
        :param u: (torch.Tensor, shape=[batchsize, nx])
        :return: (torch.Tensor, shape=[batchsize, nx])
        """
        x = self.K(x) + u
        return x


# In[ ]:


# symbolic Koopman model with control inputs
Koopman = Node(Koopman_control(K), ['x', 'u_latent'], ['x'], name='K')

# latent Koopmann rollout
dynamics_model = System([Koopman], name='Koopman', nsteps=nsteps)


# In[ ]:


# dynamics_model.show()


# In[ ]:


# put all nodes of the Koopman model together in a list of nodes
nodes = [encode_Y0, encode_Y, encode_U, dynamics_model, decode_y]


# ## Define Koopman system identification loss function terms
# 
# Here we define loss function terms to fit the encoded-decoder Koopman parameters $\theta$ from given time-series data.
# The loss function terms follow the implementation as given in the reference [[2]](https://www.nature.com/articles/s41467-018-07210-0). 
# 
# **Output trajectory prediction loss:**  
# $$\ell_y = \sum_{k=1}^{N} Q_y||y^i_{k+1} - \hat{y}^i_{k+1}||_2^2$$ 
# **One step output prediction loss:**  
# $$\ell_{y_1} = Q_{y_1}||y^i_2 - \hat{y}^i_2||_2^2$$ 
# 
# where $\hat{y}^i_{k+1} = \phi^{-1}_{\theta_3}(K^k_{\theta_2}(\phi_{\theta_1}(y^i_1))) $, 
# and $N$ is defining length of the rollout (prediction) horizon.  
# 
# **Latent trajectory prediction loss:**  
# $$\ell_{\text{lin}} = \sum_{k=1}^{N}  Q_x||\phi_{\theta_1}(y_{k+1}^i) - K^k\phi_{\theta_1}(y_1^i)||_2^2$$ 
# 

# In[ ]:


# variables
Y = variable("Y")  # observed
yhat = variable('yhat')  # predicted output
x_latent = variable('x_latent')  # encoded output trajectory in the latent space
u_latent = variable('u_latent')  # encoded input trajectory in the latent space
x = variable('x')  # Koopman latent space trajectory

xu_latent = x_latent + u_latent  # latent state trajectory

# output trajectory tracking loss
y_loss = 10. * (yhat[:, 1:-1, :] == Y[:, 1:, :]) ^ 2
y_loss.name = "y_loss"

# one-step tracking loss
onestep_loss = 1.*(yhat[:, 1, :] == Y[:, 1, :])^2
onestep_loss.name = "onestep_loss"

# reconstruction loss
reconstruction_loss = 20.*(yhat[:, 0, :] == Y[:, 0, :])^2
reconstruction_loss.name = "reconstruction_loss"

# latent trajectory tracking loss
x_loss = 1. * (x[:, 1:-1, :] == xu_latent[:, 1:, :]) ^ 2
x_loss.name = "x_loss"


# ## Construct System ID learning problem
# 
# Given the training dataset $\hat{X} = [\hat{x}^i_0, ..., \hat{x}^i_{N}]$ we want to solve the following problem:
#  
# $$
# \begin{align}
# &\underset{\theta}{\text{minimize}}     && \sum_{i=1}^m \Big( \ell_{y} + \ell_{y_1}  +\ell_{\text{lin}} + \ell_{\text{recon}} + \ell_{\text{stable}} \Big) \\
# &\text{subject to}    && \hat{y}^i_{k+1} = \phi^{-1}_{\theta_3}(K^k_{\theta_2}(\phi_{\theta_1}(y_1^i))) \\
# \end{align}
# $$  

# In[ ]:


# aggregate list of objective terms and constraints
objectives = [y_loss, x_loss, onestep_loss, reconstruction_loss]

if stable:
    objectives.append(K_reg_loss)

# create constrained optimization loss
loss = PenaltyLoss(objectives, constraints=[])

# construct constrained optimization problem
problem = Problem(nodes, loss)


# In[ ]:


# plot computational graph
#problem.show()
print(problem.input_keys)
print(problem.output_keys)


# In[ ]:


problem(next(iter(train_loader)))


# ## Solve the problem
# 
# We fit the unknown NODE parameters $\theta$ using stochastic gradient descent.

# In[ ]:


optimizer = torch.optim.Adam(problem.parameters(), lr=0.001)

trainer = Trainer(
    problem,
    train_loader,
    dev_loader,
    test_data,
    optimizer,
    patience=200,
    warmup=100,
    epochs=2000,
    eval_metric="dev_loss",
    train_metric="train_loss",
    dev_metric="dev_loss",
    test_metric="dev_loss",
)


# In[ ]:


# %% train
start = tim.time()
best_model = trainer.train()
problem.load_state_dict(best_model)
end = tim.time()


# In[ ]:


import datetime

# Generate a string with the current timestamp
#timestamp_str = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

#torch.save(best_model, "./data/model_" + timestamp_str + ".pth")


# In[ ]:


torch.save(best_model, "./data/model_noC.pth")


# In[ ]:


# load problem
#problem.load_state_dict(torch.load('data/model_20241028_105952.pth'),strict=False)


# In[ ]:


# elapsed time
# print(f"Elapsed time train: {end-start:.2f} sec")


# ## System Identification results

# In[ ]:


problem.nodes


# In[ ]:


# update the rollout length based on the test data
problem.nodes[3].nsteps = 2000


# In[ ]:


# Test set results
start = tim.time()
test_outputs = problem.step(test_data)
end = tim.time()
print(f"Elapsed time test: {end-start:.2f} sec")

pred_traj = test_outputs['yhat'][:, 1:-1, :].detach().numpy().reshape(-1, nx).T
true_traj = test_data['Y'][:, 1:pred_traj.shape[1]+1, ].detach().numpy().reshape(-1, nx).T
input_traj = test_data['U'].detach().numpy().reshape(-1, nu).T
pred_x = test_outputs['x'][:, 1:-1, :].detach().numpy().reshape(-1, nx_koopman).T


# In[ ]:


test_data['Y'].shape


# In[ ]:


test_data['Y'][:, 1:pred_traj.shape[1]+1, ].shape


# In[ ]:


test_outputs['yhat'][:, 1:-1, :].shape


# In[ ]:


pred_x.shape


# In[ ]:





# In[ ]:


test_data['Y'][:, 1:pred_traj.shape[1]+1, ].shape


# In[ ]:


np.mean((pred_traj - true_traj) ** 2)
#2*60; 40 0.06774564
#3*60 80 0.05942205
# 16 32 64 40 0.06478106
# 16 32 64 64 0.06103883
# 16 32 64 128 0.07568752
# 32 64 128 128 0.061701212

# 0.00673042


# In[ ]:


from scipy.signal import cont2discrete

# Given parameters
gain = 1.313    # Example gain
tau = 43  # Example time constant
T = 1    # Sampling time (choose based on your application)

# Continuous-time state-space matrices
A = np.array([[-1/tau]])
B = np.array([[gain/tau]])
C = np.array([[1]])
D = np.array([[0]])

# Discretize using cont2discrete
system = (A, B, C, D)
discrete_system = cont2discrete(system, T, method='zoh')

# Extract discrete-time matrices
A_d, B_d, C_d, D_d, _ = discrete_system

print("Discrete A matrix:", A_d)
print("Discrete B matrix:", B_d)
print("Discrete C matrix:", C_d)
print("Discrete D matrix:", D_d)


# In[ ]:


input_traj[:,30]


# In[ ]:


x0 = test_data['Y0'][0].detach().numpy()
input_traj = test_data['U'].detach().numpy()
y_strejc = np.zeros((nx, 2001))
y_strejc[:, 0] = x0
for i in range(2000):
    y_strejc[:,i+1] = A_d @ y_strejc[:,i] + B_d @ input_traj[:,i]


# In[ ]:


x_enc = problem.nodes[0]({"Y0": test_data['Y'][:, 1:pred_traj.shape[1]+1, ]})#({"Y0": torch.from_numpy(pred_traj.reshape(1,-1,1)).float()})
y_endec = problem.nodes[4](x_enc)
y_ed = y_endec['yhat'][0].detach().numpy()


# In[ ]:


# plot trajectories
figsize = 25
fig, ax = plt.subplots(nx + nu, figsize=(figsize, figsize))
part = 2000

x_labels = [f'$y_{k}$' for k in range(len(true_traj))]
for row, (t1, t2, t3, t4, label) in enumerate(zip(true_traj, pred_traj, y_strejc, y_ed.T, x_labels)):
    axe = ax[row]
    axe.set_ylabel(label, rotation=0, labelpad=20, fontsize=figsize)
    axe.plot(t1[:part], 'c', linewidth=4.0, label='True')
    axe.plot(t2[:part], 'm--', linewidth=4.0, label='Pred')
    axe.plot(t3[:part], 'r--', linewidth=4.0, label='Strejc')
    #axe.plot(t4[:part], 'r-', linewidth=4.0, label='endec')
    axe.tick_params(labelbottom=False, labelsize=figsize)
axe.tick_params(labelbottom=True, labelsize=figsize)
axe.legend(fontsize=figsize)

u_labels = [f'$u_{k}$' for k in range(len(input_traj))]
for row, (u, label) in enumerate(zip(input_traj, u_labels)):
    axe = ax[row+nx]
    axe.plot(u[:part], linewidth=4.0, label='inputs')
    axe.legend(fontsize=figsize)
    axe.set_ylabel(label, rotation=0, labelpad=20, fontsize=figsize)
    axe.tick_params(labelbottom=True, labelsize=figsize)

ax[-1].set_xlabel('$time$', fontsize=figsize)
plt.tight_layout()


# In[ ]:


true_traj[0,0]


# In[ ]:


from filterpy.kalman import UnscentedKalmanFilter as UKF
from filterpy.kalman import MerweScaledSigmaPoints
A_noC = K.weight.detach().numpy()
B_noC = f_u.weight.detach().numpy()

def get_y_noC(x):
    y = problem.nodes[4]({"x": torch.from_numpy(x.T).float()})
    return y["yhat"][0].detach().numpy().reshape(1,-1).T

# Define the state transition function (Linear)
def f_cv(state, u):
    x = state.reshape(-1,1)
    x_new = A_noC@x + B_noC*u
    return x_new.flatten()

# Define the measurement function (Nonlinear)
def h_nonlinear(state):
    y = get_y_noC(state)
    return y.flatten()

# Define UKF parameters
dt = 1.0  # Time step
dim_x = 10  # Number of states [position, velocity]
dim_z = 1  # Number of measurements (nonlinear function of position)

# Create sigma points generator
sigmas = MerweScaledSigmaPoints(n=dim_x, alpha=0.1, beta=2.0, kappa=0)

# Initialize UKF
ukf = UKF(dim_x=dim_x, dim_z=dim_z, fx=f_cv, hx=h_nonlinear, dt=dt, points=sigmas)

# Set initial state and covariance
ukf.x = pred_x[:,0]  # Initial state: [position=2, velocity=1]
ukf.P = np.eye(dim_x) * 0.1  # Initial uncertainty

# Process and measurement noise
ukf.Q = np.eye(dim_x) * 0.01  # Process noise
ukf.R = np.eye(dim_z) * 0.1   # Measurement noise

# Simulate measurements
num_steps = 3599
true_states = []
measurements = []
estimated_states = []

for k in range(num_steps):
    u_k = input_traj[:,k]
    # Simulate true state
    true_state = f_cv(ukf.x, u_k)
    true_states.append(true_state)
    
    # Simulate nonlinear measurement with noise
    measurement = true_traj[0,k] #+ np.random.normal(0, 0.01)
    measurements.append(measurement)
    
    # UKF update step
    ukf.predict(dt=u_k)

    ukf.update(measurement)
    # Store estimates
    estimated_states.append(ukf.x.copy())

# Convert lists to arrays for plotting
true_states = np.array(true_states)
measurements = np.array(measurements)
estimated_states = np.array(estimated_states)


# In[ ]:


error = 0
error_ukf = 0
for i in range(nx_koopman):
    # plot lifted space traj, pred_x and x_enc for comparison
    plt.figure(figsize=(25, 5))
    plt.plot(pred_x[i, :part], 'm--', linewidth=4.0, label='Pred')
    plt.plot(estimated_states[:, i], label="Estimated Position", marker="o")
    plt.plot(x_enc['x'][0].detach().numpy()[:, i][:part], 'c', linewidth=4.0, label='Enc_back')
    plt.legend(fontsize=figsize)
    error = error + np.mean((pred_x[i, :part] - x_enc['x'][0].detach().numpy()[:, i][:part]) ** 2)
    error_ukf = error_ukf + np.mean((pred_x[i, :part-1] - estimated_states[:, i][:part-1]) ** 2)
# print total mse
print(error/nx_koopman)
print(error_ukf/nx_koopman)     
# mse = 0.1854 for latent 1, pred 80
# mse = 0.1633 for latent 10, pred 80
# mse = 0.1653 for latent 10, pred 200
print(x_enc['x'][0].detach().numpy()[:, :][0])
print(pred_x[:,0])


# In[ ]:





# 

# In[ ]:


A = K.weight.detach().numpy()
B = f_u.weight.detach().numpy()

np.save('./data/A_noC.npy', A)
np.save('./data/B_noC.npy', B)
#np.save('./data/C_DeReK_False.npy', C)


# In[ ]:





# In[ ]:


def controllability_test(A, B):
    """
    Test the controllability of a system given state-space matrices A and B.

    Parameters:
    A (ndarray): State matrix of size (n, n)
    B (ndarray): Input matrix of size (n, m)

    Returns:
    bool: True if the system is controllable, False otherwise.
    """
    n = A.shape[0]  # Number of states
    controllability_matrix = B
    
    # Compute [B, AB, A^2B, ..., A^(n-1)B]
    for i in range(1, n):
        controllability_matrix = np.hstack((controllability_matrix, np.linalg.matrix_power(A, i) @ B))
    
    # Check rank of the controllability matrix
    rank = np.linalg.matrix_rank(controllability_matrix)
    return rank == n

is_controllable = controllability_test(A, B)
print(f"System is controllable: {is_controllable}")

def analyze_controllability(A, B):
    n = A.shape[0]
    controllability_matrix = B
    for i in range(1, n):
        controllability_matrix = np.hstack((controllability_matrix, np.linalg.matrix_power(A, i) @ B))
    
    rank = np.linalg.matrix_rank(controllability_matrix)
    return controllability_matrix, rank

C_matrix, rank = analyze_controllability(A, B)
print("Controllability Matrix:")
print(C_matrix)
print(f"Rank: {rank}/{A.shape[0]}")



# In[ ]:


# compute Koopman eigenvalues and eigenvectors
if stable:
    eig, eig_vec = torch.linalg.eig(K.effective_W())
else:
    eig, eig_vec = torch.linalg.eig(K.weight)
# Koopman eigenvalues real and imaginary parts
eReal = eig.real.detach().numpy()
eImag = eig.imag.detach().numpy()
# unit circle
t = np.linspace(0.0, 2 * np.pi, 1000)
x_circ = np.cos(t)
y_circ = np.sin(t)


# In[ ]:


eigenvalues, eigenvectors = np.linalg.eig(A)

# Find the index of the dominant eigenvalue (largest magnitude)
dominant_index = np.argmax(np.abs(eigenvalues))

# Extract the dominant eigenvalue and corresponding eigenvector
dominant_eigenvalue = eigenvalues[dominant_index]
dominant_eigenvector = eigenvectors[:, dominant_index]

print("dominant eigenvalue is at index", dominant_index)
print("\nDominant Eigenvalue:", dominant_eigenvalue)
print("Corresponding Dominant Eigenvector:")
print(dominant_eigenvector)


# In[ ]:


A[:,0]


# In[ ]:


# plot Koopman eigenvalues
fig1, ax1 = plt.subplots()
ax1.plot(x_circ, y_circ, 'c', linewidth=4)
ax1.plot(eReal, eImag, 'wo')
ax1.set_aspect('equal', 'box')
ax1.set_facecolor("navy")
ax1.set_xlabel("$Re(\lambda)$", fontsize=figsize)
ax1.set_ylabel("$Im(\lambda)$", fontsize=figsize)
fig1.suptitle('Koopman operator eigenvalues')


# In[ ]:


# compute Koopman state eigenvectors
y_min = 1.1*test_data['Y'].min()
y_max = 1.1*test_data['Y'].max()
y1 = torch.linspace(y_min, y_max, 1000)
y2 = torch.linspace(y_min, y_max, 1000)
yy1, yy2 = torch.meshgrid(y1, y1)
plot_yy1 = yy1.detach().numpy()
plot_yy2 = yy2.detach().numpy()
# eigenvectors
features = torch.stack([yy1, yy2]).transpose(0, 2)
latent = f_y(features)
phi = torch.matmul(latent, abs(eig_vec))
# select first 6 eigenvectors
phi_1 = phi.detach().numpy()[:,:,0]
phi_2 = phi.detach().numpy()[:,:,1]
phi_3 = phi.detach().numpy()[:,:,2]
phi_4 = phi.detach().numpy()[:,:,3]
phi_5 = phi.detach().numpy()[:,:,4]
phi_6 = phi.detach().numpy()[:,:,6]


# In[ ]:


# plot eigenvectors
fig2, axs = plt.subplots(2, 3)
im1 = axs[0,0].imshow(phi_1)
im2 = axs[0,1].imshow(phi_2)
im3 = axs[0,2].imshow(phi_3)
im4 = axs[1,0].imshow(phi_4)
im5 = axs[1,1].imshow(phi_5)
im6 = axs[1,2].imshow(phi_6)
fig2.colorbar(im1, ax=axs)
fig2.suptitle('first six eigenfunctions')


# # Optimal Control
# 

# In[ ]:


import sys
sys.path.append('../functions')

import numpy as np
from scipy.linalg import expm
import dense
import cvxpy as cp
import matplotlib.pyplot as plt


# In[ ]:





# In[ ]:


def get_x(y):
    x = problem.nodes[0]({"Y0": torch.from_numpy(y).float()})
    return x["x"].detach().numpy().reshape(1,-1).T

def get_y(x):
    y = problem.nodes[4]({"x": torch.from_numpy(x.T).float()})
    return y["yhat"][0].detach().numpy().reshape(1,-1).T

def get_vector_y(x):
    y = problem.nodes[4]({"x": torch.from_numpy(x.T).float()})
    return y["yhat"].detach().numpy().reshape(1,-1).T


# In[ ]:


x0 = get_x(np.array(([[1.0]])))
x_ = x0
for i in range(100):
    y = get_y(x_)
    x_ = get_x(y)

print(sum(x0-x_)**2)

# 1 --> 6.1389
# 10 --> 1.4665
# 100 ---> 0.00010013s


# In[ ]:


Qx = np.zeros((nx_koopman,nx_koopman))
Qx[0,0] = 1
x_for = get_x(np.array([[0]]))
Qx = np.diag( 1/(x_for[:,0]**2) )
#Qx[1,1] = 1
Qx = np.eye(nx_koopman)
Qu = np.eye(nu)*0.000001

sim_len = 400
N = 40

umax = scalerU.transform(np.array([[100]]))
umin = scalerU.transform(np.array([[20]]))

x = np.zeros((nx_koopman, sim_len+1))
u = np.zeros((nu, sim_len+1))
y = np.zeros((ny, sim_len))
#x0 = get_x(np.array([[1]]))
x_in_0 = get_x(np.array([[0]]))
# x_ = x0
# for i in range(1000):
#     x_ = A@x_ + B@scalerU.transform(np.array([[50]]))
# x_in_0 = x_
# x_ = x0[:,0]
# print(sum(x_))
# for i in range(5000):
#     x_ = A@x_ + B@scalerU.transform(np.array([[50]]))[:,0]
# print(sum(x_))

# x0 = x_.reshape(-1,1)

x0 = get_x(np.array([[1.0]]))

x[:,0] = x0[:,0]
#x0 = x0 - x_in_0


# In[ ]:


x0.shape


# In[ ]:


start = tim.time()
for i in range(sim_len):
    Q = dense.quad_form_sr(A, B, Qx, Qu, N)
    c = dense.lin_form_sr(A, B, Qx, N, x0)
    F = dense.constraint_matrix_sr_nox(N)
    g = dense.upper_bound_sr_nox(N,umax, umin)
    
    U = cp.Variable((N, nu))
    
    objective = cp.Minimize(cp.quad_form(U, Q) + c @ U)
    constraints = [F @ U <= g]
    
    problem_mpc = cp.Problem(objective, constraints)
    problem_mpc.solve()
    
    print(problem_mpc.objective.value)
    print(U.value)
    u[:, i] = U.value[0, :].reshape(-1, 1)
    
    # propagation in time
    x[:, i+1] = A @ x[:, i] + B @ u[:, i]
    y[:, i] = get_y(x[:, i+1])
    
        
    x0 = get_x(y[:,i])[:,0] #x[:, i+1] #- x_in_0[:,0] #get_x(y[:,i])[:,0]
    #print(sum(x0))
    print(i)
end = tim.time()
print(f"Elapsed time MPC: {end-start:.2f} sec")


# In[ ]:


u_desc = scalerU.inverse_transform(u.T)
plt.plot(u_desc)


# In[ ]:


y = get_vector_y(x)


# In[ ]:


y_desc = scaler.inverse_transform(y)
plt.plot(y_desc)


# In[ ]:


plt.plot(x[0,:])


# In[ ]:


for i in range(nx_koopman):
    plt.plot(x[i,:])


# In[ ]:


x[0,0]-x_in_0[0]


# # To reference

# In[ ]:


u = scalerU.transform(np.array([[30]]))[:,0]
x = get_x(scaler.transform(np.array([[36.56215]])))[:,0]
print(x)
for i in range(1000):
    x = A@x + B@u
print(x)
print(scaler.inverse_transform(get_y(x)))
print(get_x(get_y(x))[:,0])
x_store = x


# In[ ]:


# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Find the indices of the dominant eigenvalues
dominant_indices = np.argsort(-np.abs(eigenvalues))  # Sort by absolute value in descending order
dominant_eigenvalues = eigenvalues[dominant_indices]

# Output results
print("Eigenvalues:", eigenvalues)
print("Dominant Eigenvalues:", dominant_eigenvalues)
print("Indices of Dominant Eigenvalues:", dominant_indices)


# In[ ]:





# In[ ]:


Qx = np.zeros((nx_koopman,nx_koopman))
for i in range(nx_koopman):
    if dominant_indices[i] <= 5:
        Qx[i,i] = 10
    else:
        Qx[i,i] = 1
x_for = get_x(np.array([[0]]))
#Qx = np.diag( 1/(x_for[:,0]**2) )
#Qx = np.eye(nx_koopman)
Qu = np.eye(nu)*0.1

sim_len = 400
N = 40

umax = scalerU.transform(np.array([[100]]))
umin = scalerU.transform(np.array([[20]]))

x = np.zeros((nx_koopman, sim_len+1))
u = np.zeros((nu, sim_len+1))
y = np.zeros((ny, sim_len))

x_in_0 = get_x(np.array([[0]]))


x0 = get_x(scaler.transform(np.array([[60]])))
x_ref = np.array([x_store]).T #get_x(scaler.transform(np.array([[30]])))
u_prev = scalerU.transform(np.array([[20]]))

x[:,0] = x0[:,0]


# In[ ]:


start = tim.time()
for i in range(sim_len):
    Q = dense.quad_form_cr(A, B, Qx, Qu, N)
    c = dense.lin_form_cr(A, B, Qx, Qu, N, x0, x_ref, u_prev)
    F = dense.constraint_matrix_sr_nox(N)
    g = dense.upper_bound_sr_nox(N,umax, umin)
    
    U = cp.Variable((N, nu))
    
    objective = cp.Minimize(cp.quad_form(U, Q) + c @ U)
    constraints = [F @ U <= g]
    
    problem_mpc = cp.Problem(objective, constraints)
    problem_mpc.solve()
    
    print(problem_mpc.objective.value)
    #print(U.value)
    u[:, i] = U.value[0, :].reshape(-1, 1) #scalerU.transform(np.array([[75]]))#U.value[0, :].reshape(-1, 1)
    
    # propagation in time
    x[:, i+1] = A @ x[:, i] + B @ u[:, i]
    y[:, i] = get_y(x[:, i+1])
    
        
    x0 = get_x(y[:,i])[:,0] #x[:, i+1] #- x_in_0[:,0] #get_x(y[:,i])[:,0]
    u_prev = u[:,i]
    #print(sum(x0))
    print(i)
end = tim.time()
print(f"Elapsed time MPC: {end-start:.2f} sec")


# In[ ]:


plt.plot(scalerU.inverse_transform(u.T))


# In[ ]:





# In[ ]:


y = get_vector_y(x)


# In[ ]:





# In[ ]:


y_desc = scaler.inverse_transform(y)
plt.plot(y_desc)


# In[ ]:


y_desc[-1]


# In[ ]:


scaler.inverse_transform(get_y(x_ref))


# In[ ]:


plt.plot(x[0,:])
plt.axhline(y = x_ref[0], linestyle = '--') 


# In[ ]:


plt.plot(x[1,:])
plt.axhline(y = x_ref[1], linestyle = '--') 


# In[ ]:


plt.plot(x[2,:])
plt.axhline(y = x_ref[2], linestyle = '--') 


# In[ ]:


plt.plot(x[3,:])
plt.axhline(y = x_ref[3], linestyle = '--') 


# In[ ]:


for i in range(nx_koopman):
    plt.plot(x[i,:])
    
plt.axhline(y = x_ref[1], linestyle = '--') 
plt.axhline(y = x_ref[0], linestyle = '--') 
    


# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:




